// test/docs-images-brand.test.mjs -- the README images under
// docs/assets/brand/ that are screenshots (04-board.png, 05-viewer.png)
// must come from the generator AND their source files must be in the
// freshness list. Until 2026-10-01 both were hand-made, outside the
// generator and outside UI_FILES, so they went stale unnoticed.
// No browser needed.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as d from '../src/docimages-state.mjs';

const REPO = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(REPO, p), 'utf8');

test('positive control: the README references the brand images this probe looks for', () => {
  const names = [...read('README.md').matchAll(/docs\/assets\/brand\/(\d\d-[\w-]+\.png)/g)].map((m) => m[1]);
  assert.ok(names.includes('04-board.png'));
  assert.ok(names.includes('05-viewer.png'));
});

test('board and viewer sources are in the freshness list (UI_FILES)', () => {
  const l = d.uiFiles(REPO);
  assert.ok(l.includes('src/board.mjs'), 'src/board.mjs');
  assert.ok(l.includes('src/viewer.mjs'), 'src/viewer.mjs');
});

test('every README brand screenshot is produced by bench/docs-images.mjs', () => {
  const script = read('bench/docs-images.mjs');
  const names = new Set([...read('README.md').matchAll(/docs\/assets\/brand\/(\d\d-[\w-]+\.png)/g)].map((m) => m[1]));
  for (const n of names) {
    // 01-03 are drawn from an .svg source next to the png; every other
    // numbered brand image is a screenshot and must be generated.
    if (fs.existsSync(path.join(REPO, 'docs/assets/brand', n.replace(/\.png$/, '.svg')))) continue;
    assert.ok(script.includes(n), `${n} is referenced by the README but not generated by bench/docs-images.mjs`);
    assert.ok(fs.existsSync(path.join(REPO, 'docs/assets/brand', n)), `${n} missing`);
  }
});

test('README no longer claims "three states" next to the board', () => {
  const readme = read('README.md');
  const at = readme.indexOf('## What it looks like');
  const section = readme.slice(at, readme.indexOf('\n## ', at + 5));
  assert.ok(!/three states/i.test(section));
  assert.match(section, /four states/i);
});
