/**
 * Installing the git hook, and proving it runs.
 *
 * Split out of `bin/mem` on 2026-09-18 together with the CLI shell. This
 * block sat BELOW the command table and worked only because function
 * declarations hoist — which is to say: the file was held together by a
 * language rule, not by a structure anyone could see.
 *
 * The memory is the user's data repository; this package is the tool.
 * They live in different places, so the hook cannot simply be a file in
 * the repo — it has to know where the redaction module is. So we
 * generate it, with the package path baked in.
 */

import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import { execFileSync, spawnSync } from 'node:child_process';
import * as observations from '../observations.mjs';
import { PKG_ROOT } from './shell.mjs';

export function canExecuteIn(dir) {
  // Windows has no execve and no noexec mounts: git for Windows starts
  // hooks by handing the file to its bundled sh. The probe below would
  // always fail there (a extensionless script is not an executable
  // image) and send the hook off to a fallback directory for a problem
  // that does not exist on that platform.
  if (process.platform === 'win32') return true;
  const probe = path.join(dir, `.exec-probe.${process.pid}`);
  try {
    fs.writeFileSync(probe, '#!/bin/sh\nexit 0\n');
    fs.chmodSync(probe, 0o755);
    const r = spawnSync(probe, [], { stdio: 'ignore' });
    fs.unlinkSync(probe);
    return !r.error;
  } catch {
    try { fs.unlinkSync(probe); } catch { /* fine */ }
    return false;
  }
}

export function hookBody() {
  // CHEAP_MEM_PKG tells the shared script where the redaction module
  // lives. Without it the script cannot find it and — in an earlier
  // version — exited 0, reporting success while checking nothing.
  // The hook is a shell script, so the paths in it have to be shell
  // paths. On Windows `path.join` yields backslashes, JSON.stringify
  // doubles them, and bash then eats them again — C:\\x\\y arrives as
  // C:xy. Forward slashes work for both bash and node on every platform.
  const shellPath = (p) => JSON.stringify(p.split(path.sep).join('/'));
  return `#!/usr/bin/env bash
# pre-commit — third line of defence against secrets. Generated by
# \`mem hooks install\`; the logic lives in the cheap-mem package.
export CHEAP_MEM_PKG=${shellPath(PKG_ROOT)}
exec bash ${shellPath(path.join(PKG_ROOT, 'hooks', 'pre-commit'))} "$@"
`;
}

export function installHook(root, dirOverride) {
  const lines = [];
  let target;

  if (dirOverride) {
    target = path.resolve(dirOverride);
    fs.mkdirSync(target, { recursive: true });
  } else if (canExecuteIn(root)) {
    lines.push('Memory mount allows execve — installing inside the memory.');
    target = path.join(root, '.mem', 'hooks');
    fs.mkdirSync(target, { recursive: true });
  } else {
    // git starts hooks with execve. On a noexec mount the kernel
    // refuses even though the x-bit is set, git prints "hook was
    // ignored because it's not set as executable" — and commits
    // anyway. chmod cannot fix it; the hook has to live elsewhere.
    lines.push('Memory mount forbids execve (noexec?) — installing outside the memory.');
    // `process.env.HOME ?? '/tmp'` stood here until 2026-09-19. On
    // Windows HOME is normally unset — the home directory is USERPROFILE
    // — so the fallback fired and the hook was written to `C:\tmp\`,
    // a directory that usually does not exist and belongs to nobody.
    // Found while triaging a Windows bug report the same day.
    // `os.homedir()` is the one answer that is right on all three
    // platforms: it reads $HOME on POSIX (so an overridden HOME in a
    // test still works) and USERPROFILE on Windows.
    target = path.join(os.homedir(), '.cheap-mem-hooks');
    fs.mkdirSync(target, { recursive: true });
  }

  const hookPath = path.join(target, 'pre-commit');
  fs.writeFileSync(hookPath, hookBody());
  fs.chmodSync(hookPath, 0o755);

  if (!canExecuteIn(target)) {
    lines.push(`  ${target} is not executable either.`);
    lines.push('  Pick another place: mem hooks install --dir /some/path');
    return { ok: false, lines };
  }

  try {
    execFileSync('git', ['-C', root, 'config', 'core.hooksPath', target], { stdio: 'ignore' });
  } catch (e) {
    lines.push(`  could not set core.hooksPath: ${e.message}`);
    lines.push('  Is the memory a git repository? (git init)');
    return { ok: false, lines };
  }
  lines.push(`Hook written: ${hookPath}`);
  lines.push(`core.hooksPath = ${target}`);
  lines.push('');

  const proof = proveHook(root);
  lines.push(...proof.lines);
  return { ok: proof.ok, lines };
}

/**
 * Prove the hook fires, using a decoy secret in a THROWAWAY index.
 * Neither the real index nor the history is touched.
 *
 * "Configured, therefore fine" is exactly the mistake this whole
 * design exists to avoid: a hook can be configured perfectly and still
 * never run.
 */
export function proveHook(root) {
  const lines = ['Test: does the hook catch a planted token?'];
  let set;
  try {
    set = execFileSync('git', ['-C', root, 'config', '--get', 'core.hooksPath'],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch { set = ''; }
  if (!set) {
    lines.push('  core.hooksPath is not set — run: mem hooks install');
    return { ok: false, lines };
  }
  const hookPath = path.isAbsolute(set) ? path.join(set, 'pre-commit') : path.join(root, set, 'pre-commit');
  if (!fs.existsSync(hookPath)) {
    lines.push(`  ${hookPath} is missing — run: mem hooks install`);
    return { ok: false, lines };
  }

  const decoy = path.join(root, `.decoy-probe.${process.pid}`);
  const tmpIndex = path.join(os.tmpdir(), `cheap-mem-index-${process.pid}`);
  fs.writeFileSync(decoy,
    `Decoy, not a real secret.\nghp_${'A'.repeat(36)}\n`);
  let blocked = 0;
  try {
    const env = { ...process.env, GIT_INDEX_FILE: tmpIndex };
    spawnSync('git', ['-C', root, 'read-tree', 'HEAD'], { env, stdio: 'ignore' });
    spawnSync('git', ['-C', root, 'add', '-f', decoy], { env, stdio: 'ignore' });
    // How git starts a hook differs by platform, and the point of this
    // probe is to start it the same way git will. On unix that is
    // execve on the file itself — which is what catches a noexec
    // mount. On Windows git hands the file to its bundled bash, so
    // starting the file directly would always fail and report a
    // problem that is not there.
    const r = process.platform === 'win32'
      ? spawnSync('bash', [hookPath], { env, cwd: root, stdio: 'ignore' })
      : spawnSync(hookPath, [], { env, cwd: root, stdio: 'ignore' });
    blocked = r.error ? -1 : (r.status ?? 0);
  } finally {
    try { fs.unlinkSync(decoy); } catch { /* fine */ }
    try { fs.unlinkSync(tmpIndex); } catch { /* fine */ }
  }

  if (blocked === -1) {
    lines.push('  the hook could not be started at all (noexec mount?)');
    lines.push('  Try: mem hooks install --dir ~/.cheap-mem-hooks');
    return { ok: false, lines };
  }
  if (blocked !== 0) {
    lines.push(`  blocked (exit ${blocked}) — the third redaction layer is alive.`);
    return { ok: true, lines };
  }
  lines.push('  LET THROUGH — the hook does not catch the decoy.');
  lines.push('  The third redaction layer is NOT armed.');
  return { ok: false, lines };
}

/**
 * The memory's own .gitignore.
 *
 * **This is not tidiness, it is the difference between a key on your
 * disk and a key in a public repository.** `.mem/embed.env` holds an
 * API key; without this file the first `git add -A` commits it, and git
 * forgets nothing. Everything else here is derived state that would
 * only produce merge conflicts.
 *
 * Written on init, and merged (never overwritten) if one already
 * exists — someone's own rules must survive.
 */
/**
 * Declare the union merge driver for every drawer.
 *
 * Appends rather than overwrites: a repository may already have its own
 * .gitattributes, and clobbering it to install one line would be a poor
 * trade. Idempotent — running init twice does not duplicate the rule.
 */
export function writeMergeDriver(root) {
  const p = path.join(root, '.gitattributes');
  const rule = '*.jsonl merge=union';
  const note = [
    '# Every drawer is append-only: two sessions independently add lines at',
    '# the end of a file. A normal merge sees a conflict ("both changed the',
    '# last line") and stops -- while the right answer is always the same:',
    '# keep both. `merge=union` does exactly that.',
    '#',
    '# Do NOT use this for structured files (JSON, YAML): union would glue',
    '# two halves of an object together and destroy the file.',
    rule,
    '',
  ].join('\n');
  // Returns whether anything was written. Previously the function
  // returned nothing, and a caller could not tell whether the guarantee
  // was already in place or had just been created.
  if (!fs.existsSync(p)) { fs.writeFileSync(p, note, 'utf8'); return { added: 1, path: p }; }
  const cur = fs.readFileSync(p, 'utf8');
  if (new RegExp(`^\\s*\\*\\.jsonl\\s+merge=union\\s*$`, 'm').test(cur)) {
    return { added: 0, path: p };
  }
  fs.writeFileSync(p, `${cur.replace(/\n*$/, '')}\n\n${note}`, 'utf8');
  return { added: 1, path: p };
}

export function writeMemoryGitignore(root) {
  const p = path.join(root, '.gitignore');
  const wanted = [
    ['.mem/embed.env', 'API keys. NEVER commit this.'],
    ['.mem/epoch.json', 'Local rollback watermark. Never commit: a tracked one\n     travels back with the checkout it is meant to detect.'],
    // Beide Namen, und das ist kein Versehen. Seit B8 (2026-09-20) legt
    // `loadIndex` den Cache als VERZEICHNIS `.mem/search-index/` an;
    // `.mem/search-index.json` ist der alte Ein-Datei-Name. Ein
    // Gedaechtnis, das vor der Umstellung angelegt wurde, traegt die
    // alte Zeile in seiner .gitignore und wuerde das neue Verzeichnis
    // COMMITTEN — gemessen an genau dieser Zeile gefunden. Die alte
    // Zeile bleibt, weil eine Altdatei noch herumliegen kann.
    ['.mem/search-index.json', 'derived: rebuilt in milliseconds (old single-file name)'],
    ['.mem/search-index/', 'derived: the shard cache, rebuilt in milliseconds'],
    ['.mem/vectors.db', 'derived: rebuild with `mem embed backfill`'],
    ['.mem/raw-offsets.json', 'per-machine read positions'],
    ['.mem/digest-bell.json', 'transient'],
    ['.mem/digest.lock', 'transient'],
    ['.mem/digest.log', 'local log'],
    ['.mem/hooks/', 'generated by `mem hooks install`, machine-specific'],
    [observations.LEDGER_FILE.split(path.sep).join('/'),
      'per-machine observation ledger — retrieval/ranking never reads it'],
  ];
  const existing = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';

  // **git has no trailing comments.** `#` only starts a comment at the
  // beginning of a line; anywhere else it is part of the pattern. This
  // function used to write `<rule><padding># <why>`, which made every
  // one of the nine rules a pattern that matches nothing — including
  // the one on the first line, `.mem/embed.env`, whose whole job is to
  // keep an API key out of the repository.
  //
  // Nobody noticed because the file LOOKS right. Reported 2026-09-07
  // from a fresh Windows install, reproduced here with git itself:
  // `git check-ignore -v .mem/embed.env` said NOT IGNORED on a memory
  // straight out of `mem init`. `mem doctor` now asks git the same
  // question, so the next such break is a finding and not a surprise.
  //
  // Comments go on their own line above the rule.
  const lines = existing.split('\n');
  // A rule counts as present only if a line IS the rule. A line that
  // starts with the rule and then carries a `#` is the broken form and
  // has to go — otherwise this repair would skip exactly the files that
  // need it, and a memory written before today would stay unprotected
  // forever.
  const broken = [];
  const have = new Set();
  for (const [i, l] of lines.entries()) {
    const t = l.trim();
    if (!t || t.startsWith('#')) continue;
    if (wanted.some(([rule]) => t === rule)) { have.add(t); continue; }
    const trailing = wanted.find(([rule]) => t.startsWith(`${rule} `) && t.includes('#'));
    if (trailing) broken.push(i);
    // The old multi-line `why` also left a bare continuation line
    // behind — itself a pattern matching nothing. It has no rule in
    // front of it, so it is recognised by its text.
    else if (/^travels back with the checkout/.test(t)) broken.push(i);
  }
  const missing = wanted.filter(([rule]) => !have.has(rule));
  if (missing.length === 0 && broken.length === 0) return { added: 0, path: p, repaired: 0 };

  const kept = lines.filter((_, i) => !broken.includes(i));
  const rest = kept.join('\n').replace(/\n{3,}/g, '\n\n');
  const block = ['', '# cheap-mem: derived state and secrets'];
  for (const [rule, why] of missing) {
    for (const line of String(why).split('\n')) block.push(`# ${line.trim()}`);
    block.push(rule);
  }
  const text = block.join('\n');
  fs.writeFileSync(p, rest.trim()
    ? `${rest.replace(/\n*$/, '')}\n${text}\n` : `${text.trimStart()}\n`);
  return { added: missing.length, path: p, repaired: broken.length };
}
